# Generated by Django 5.2.5 on 2025-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=True),
        ),
    ]
