# Generated by Django 5.2.5 on 2025-08-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
