# Generated by Django 5.2.5 on 2025-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0009_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stripe_checkout_id",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Bankily", "Bankily")],
                default="Cash",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="MRU", max_length=10),
        ),
    ]
